### ISSUE TITLE
Removing the DescTools dependency

### ISSUE THREAD

**Issue by crsh** [ASarafoglou/multibridge#3]
Hi @ASarafoglou,

the depency plot I added in https://github.com/ASarafoglou/multibridge/pull/2 is also useful as a guide to review package for potentially removable dependencies. Briefly, you can look for "hot spots" in the network (big red dots), which are indicative of packages that have a lot of dependencies themselves but are potentially easy to remove (because only your package depends on them). Looking at this plot indicates that `DescTools` has a lot of dependencies but is required only by `multibridge`. I checked the code and, from what I can tell, the only function that is used is `DescTools::StrAlign()`, which seems like it could be easily replaced. I was thinking of something along these lines:

~~~r
a <- rep(1, 3)
counts <- c(3, 10, 1000)

DescTools::StrAlign(paste(a, counts, sep=' + '), sep="\\c")
~~~
~~~
[1] " 1 + 3  " " 1 + 10 " "1 + 1000"
~~~

~~~r
str_align <- function(x, y) {
  aligned_x <- formatC(x, width = max(nchar(x)))
  aligned_y <- formatC(y, width = max(nchar(y)), flag = "-")
  paste(aligned_x, aligned_y, sep=' + ')
}

str_align(a, counts)
~~~
~~~
[1] "1 + 3   " "1 + 10  " "1 + 1000"
~~~

As a side-effect, I think this should solve a problem with the current approach. See the shifting `alpha` column in this example:

~~~r
x <- c(3, 4, 10, 11, 7, 300)
# priors
a <- c(1, 1, 1, 1, 1, 1)
# restricted hypothesis
factor_levels <- c('theta1', 'theta2', 'theta3', 'theta4', 'theta5', 
                   'theta6')
Hr            <- c('theta1', '<',  'theta2', '&', 'theta3', '=', 'theta4', 
                   ',', 'theta5', '<', 'theta6')
output_total  <- multBfInformed(x, Hr, a, factor_levels, seed=2020)
summary(output_total)
~~~
~~~
[...]
Posterior Median and Credible Intervals Of Marginal Beta Distributions:
           alpha    beta    2.5%    50%  97.5%
1 theta1  1 + 3  5 + 332 0.00321 0.0108 0.0256
2 theta2  1 + 4  5 + 331 0.00479 0.0137 0.0298
3 theta3 1 + 10  5 + 325 0.01630 0.0313 0.0534
4 theta4 1 + 11  5 + 324 0.01840 0.0343 0.0571
5 theta5  1 + 7  5 + 328 0.01020 0.0225 0.0420
6 theta6 1 + 300 5 + 35  0.84700 0.8830 0.9150
~~~

This shifting does not happen with this implementation:

~~~r
cat(DescTools::StrAlign(paste(a, x, sep=' + '), sep="\\c"), sep = "\n")
~~~
~~~
 1 + 3 
 1 + 4 
1 + 10 
1 + 11 
 1 + 7 
1 + 300
~~~

~~~r
cat(matrix(str_align(a, x)), sep = "\n")
~~~
~~~
1 + 3  
1 + 4  
1 + 10 
1 + 11 
1 + 7  
1 + 300
~~~ 

This also works better with decimals:

~~~r
a <- c(1.134314, 1, 1, 1, 1, 1)
cat(DescTools::StrAlign(paste(a, x, sep=' + '), sep="\\c"), sep = "\n")
~~~
~~~
1.134314 + 3
   1 + 4    
   1 + 10   
   1 + 11   
   1 + 7    
  10 + 300
~~~

~~~r
cat(matrix(str_align(a, x)), sep = "\n")
~~~
~~~
   1.134 + 3  
       1 + 4  
       1 + 10 
       1 + 11 
       1 + 7  
      10 + 300
~~~

If that sounds good to you, I'd be happy to open another PR.

**Comment by ASarafoglou** [comment]
yes, I agree with these changes! seems like the better solution.
